import { useState } from 'react'
import { Activity, ArrowRight, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useLab, type AuditEvent } from '../store/LabContext'
import { Eyebrow, Panel, Status } from '../components/ui'

export function AuditPage() {
  const { auditEvents } = useLab()
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<AuditEvent | null>(null)
  const [filter, setFilter] = useState<'all' | 'success' | 'denied' | 'info'>('all')
  const filtered = auditEvents.filter(event => (filter === 'all' || event.result === filter) && `${event.type} ${event.application} ${event.method}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="page-container audit-page"><div className="page-heading"><Eyebrow>OBSERVABILITY</Eyebrow><h1>Audit trail<span>.</span></h1><p>Every meaningful action in the lab becomes a structured event. Select one to inspect its data.</p></div><div className="audit-summary"><div><Activity size={19} /><strong>{auditEvents.length}</strong><span>Total events</span></div><div><span className="summary-dot success" /><strong>{auditEvents.filter(e => e.result === 'success').length}</strong><span>Successful</span></div><div><span className="summary-dot denied" /><strong>{auditEvents.filter(e => e.result === 'denied').length}</strong><span>Denied</span></div></div><Panel className="audit-panel"><div className="audit-toolbar"><div className="search-field"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search events or applications" aria-label="Search audit events" /></div><div className="segmented audit-filter" role="group" aria-label="Filter events">{(['all', 'success', 'denied', 'info'] as const).map(value => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div></div><div className="audit-layout"><div className="event-list">{filtered.length === 0 ? <div className="empty-events">No matching events. <Link to="/journey/password">Try a journey interaction <ArrowRight size={14} /></Link></div> : filtered.map(event => <button key={event.id} className={`event-row ${selected?.id === event.id ? 'event-selected' : ''}`} onClick={() => setSelected(event)}><span className={`event-indicator ${event.result}`} /><div><strong>{event.type.replaceAll('_', ' ')}</strong><small>{event.application} · {event.method}</small></div><div className="event-meta"><Status tone={event.result === 'success' ? 'good' : event.result === 'denied' ? 'bad' : 'neutral'}>{event.result}</Status><time dateTime={event.timestamp}>{new Date(event.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</time></div></button>)}</div><aside className="event-inspector"><div className="inspector-heading"><strong>EVENT INSPECTOR</strong><span>JSON</span></div>{selected ? <><h3>{selected.type}</h3><p>{selected.application} · {new Date(selected.timestamp).toLocaleString()}</p><pre>{JSON.stringify(selected, null, 2)}</pre></> : <div className="inspector-empty">Select an event to inspect its structured metadata.</div>}</aside></div></Panel><p className="page-note">These events exist only in browser memory and reset when the page reloads. Production audit systems need retention, access control, integrity, and privacy safeguards.</p></div>
}
