import { useState } from 'react'
import { ArrowRight, Fingerprint, KeyRound, ShieldCheck, UserRound } from 'lucide-react'
import { useLab, type Role } from '../../store/LabContext'
import { Button, Flow, Insight, Status } from '../ui'
import { CodeBlock, DemoFrame, Result } from './DemoPrimitives'

const passkeySteps = [
  'Boo Identity generates a fresh challenge',
  'Browser confirms the Boo Identity origin',
  'Alex approves with biometric or PIN',
  'Authenticator private key signs challenge',
  'Boo Identity verifies with public key',
]

export function PasskeyDemo() {
  const lab = useLab()
  const [step, setStep] = useState(-1)
  const [compare, setCompare] = useState<'password' | 'totp' | 'passkey'>('passkey')
  function advance() { const next = Math.min(step + 1, 4); setStep(next); if (next === 4) lab.authenticatePasskey() }
  return <div className="demo-stack"><DemoFrame title="Boo Identity / Passkey sign-in" subtitle="Follow an illustrative WebAuthn authentication ceremony." badge="07 / Passwordless"><div className="key-pair"><div><div className="key-icon"><Fingerprint size={23} /></div><strong>Alex’s authenticator</strong><Status tone="good">Private key stays here</Status></div><div className="key-connection"><span>signed challenge</span><ArrowRight size={26} /></div><div><div className="key-icon public"><KeyRound size={22} /></div><strong>Boo Identity</strong><Status>Stores public key</Status></div></div><Flow steps={passkeySteps} active={step} /><div className="action-row mt-5"><Button onClick={advance} disabled={step === 4}>{step < 0 ? 'Start passkey sign-in' : step === 4 ? 'Sign-in complete' : 'Continue ceremony'} <ArrowRight size={15} /></Button><Button variant="ghost" onClick={() => setStep(-1)}>Replay</Button></div>{step === 4 && <Result success title="Alex authenticated with a passkey">No password was transmitted. Boo Identity verified proof of the private key.</Result>}</DemoFrame><div className="mini-card"><div className="mini-heading">Compare authentication methods</div><div className="segmented" role="group" aria-label="Authentication method comparison">{(['password', 'totp', 'passkey'] as const).map(method => <button key={method} className={compare === method ? 'active' : ''} onClick={() => setCompare(method)}>{method === 'totp' ? 'TOTP' : method[0].toUpperCase() + method.slice(1)}</button>)}</div><div className="comparison-detail"><h3>{compare === 'password' ? 'Shared secret' : compare === 'totp' ? 'Second factor' : 'Public-key credential'}</h3><p>{compare === 'password' ? 'The user proves knowledge of a reusable secret. Phishing and reuse remain risks.' : compare === 'totp' ? 'A time-based code makes a stolen password insufficient, but live codes can still be phished.' : 'A private key signs a challenge for the legitimate relying party. A lookalike origin cannot use that credential.'}</p></div></div><Insight label="Passkeys + OIDC together">A passkey answers how Boo Identity authenticates Alex. OIDC answers how Expense Portal trusts the identity Boo Identity established. They work together.</Insight><div className="mini-card combined-flow"><Flow steps={['Expense Portal', 'OIDC redirect', 'Boo Identity', 'Passkey authenticates Alex', 'Boo Identity issues tokens', 'Expense Portal trusts identity']} direction="horizontal" /></div></div>
}

const permissions = ['expenses:read', 'expenses:approve', 'reports:read', 'users:manage'] as const
const rolePermissions: Record<Role, string[]> = {
  Employee: ['expenses:read'],
  Manager: ['expenses:read', 'expenses:approve', 'reports:read'],
  Administrator: [...permissions],
}

export function AuthorizationDemo() {
  const lab = useLab()
  const [role, setRole] = useState<Role>('Manager')
  const [request, setRequest] = useState('DELETE /users/42')
  const [result, setResult] = useState<'allow' | 'deny' | null>(null)
  const required = request === 'DELETE /users/42' ? 'users:manage' : request === 'POST /expenses/approve' ? 'expenses:approve' : 'expenses:read'
  function evaluate() { const allowed = rolePermissions[role].includes(required); setResult(allowed ? 'allow' : 'deny'); lab.complete('authorization'); lab.log({ type: allowed ? 'ACCESS_GRANTED' : 'ACCESS_DENIED', application: request.includes('users') ? 'Admin API' : 'Expense API', result: allowed ? 'success' : 'denied', method: 'RBAC permission check', metadata: { role, request, requiredPermission: required, status: allowed ? 200 : 403 } }) }
  return <div className="demo-stack"><div className="two-col-cards"><div className="mini-card"><UserRound size={20} /><h3>Authentication</h3><p>Who are you?</p></div><div className="mini-card accent-card"><ShieldCheck size={20} /><h3>Authorization</h3><p>What are you allowed to do?</p></div></div><DemoFrame title="Boo Corp / Permission matrix" subtitle="Select a role, then try a protected operation." badge="08 / Access control"><div className="table-wrap"><table className="permission-table"><thead><tr><th scope="col">Permission</th><th scope="col">Employee</th><th scope="col">Manager</th><th scope="col">Administrator</th></tr></thead><tbody>{permissions.map(permission => <tr key={permission}><th scope="row"><code>{permission}</code></th>{(['Employee', 'Manager', 'Administrator'] as Role[]).map(r => <td key={r}>{rolePermissions[r].includes(permission) ? <span className="yes-mark">✓ <span className="sr-only">Allowed</span></span> : <span className="no-mark">— <span className="sr-only">Not allowed</span></span>}</td>)}</tr>)}</tbody></table></div><div className="controls-grid"><label>Acting as<select value={role} onChange={e => { setRole(e.target.value as Role); setResult(null) }}><option>Employee</option><option>Manager</option><option>Administrator</option></select></label><label>API operation<select value={request} onChange={e => { setRequest(e.target.value); setResult(null) }}><option>DELETE /users/42</option><option>POST /expenses/approve</option><option>GET /expenses</option></select></label></div><Button onClick={evaluate}>Send request <ArrowRight size={15} /></Button>{result && <Result success={result === 'allow'} title={result === 'allow' ? 'Permission granted' : 'Access denied'} code={result === 'allow' ? '200 OK' : '403 Forbidden'}>Authentication: ✓ · Authorization: {result === 'allow' ? '✓' : '✗'} · Required permission: <code>{required}</code></Result>}</DemoFrame><div className="mini-card"><div className="mini-heading">Claims → policy decision</div><div className="claims-row"><span>Alex Morgan<br /><small>sub · email · department</small></span><ArrowRight size={18} /><span>Authorization claims<br /><small>role · scope</small></span><ArrowRight size={18} /><span>Policy decision<br /><small>Allow / Deny</small></span></div><CodeBlock label="Optional attribute-based policy">role == manager AND<br />expense.department == user.department AND<br />expense.amount &lt; 10000</CodeBlock></div></div>
}

export function OperationsDemo() {
  const lab = useLab()
  const [recovery, setRecovery] = useState(false)
  const [rotated, setRotated] = useState(false)
  return <div className="demo-stack"><DemoFrame title="Identity operations console" subtitle="Contain access, observe events, and plan safe recovery." badge="09 / Operations"><div className="ops-grid"><div className="ops-card"><div className="mini-heading">Active session</div><strong>{lab.sessionActive ? 'A82F2381 · Alex Morgan' : 'No active session'}</strong><p>{lab.sessionActive ? 'Server-side record can be deleted immediately.' : 'Create one in the Sessions stage to try revocation here.'}</p><Button variant="secondary" disabled={!lab.sessionActive} onClick={() => { lab.revokeSession(); lab.complete('operations') }}>Revoke session</Button></div><div className="ops-card"><div className="mini-heading">Refresh-token family</div><strong>{rotated ? 'Token B active' : 'Token A active'}</strong><p>Rotation invalidates the previous refresh token after use.</p><Button variant="secondary" onClick={() => { setRotated(true); lab.complete('operations'); lab.log({ type: 'TOKEN_REFRESHED', application: 'Boo Identity', result: 'success', method: 'refresh-token rotation', metadata: { old: 'A', new: 'B' } }) }}>{rotated ? 'Rotate again' : 'Rotate token'}</Button></div><div className="ops-card"><div className="mini-heading">Account recovery</div><strong>{recovery ? 'Recovery reviewed' : 'Fallback needed'}</strong><p>Recovery is an alternative route into the account and needs strong verification.</p><Button variant="secondary" onClick={() => { setRecovery(true); lab.complete('operations'); lab.log({ type: 'RECOVERY_REVIEWED', application: 'Boo Identity', result: 'info', method: 'simulation', metadata: { concept: 'one-time recovery code' } }) }}>Review recovery</Button></div></div><div className="mt-6"><Result success title={`${lab.auditEvents.length} audit events in this visit`}>Open Audit to inspect structured events generated by your interactions.</Result></div></DemoFrame><Insight label="Operational reality" tone="amber">Production audit logs require access controls, retention rules, integrity protections, and careful handling of personal data. These demo events live only in memory.</Insight></div>
}
